// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresApp;

namespace CardsGame.Migrations.Colod
{
    [DbContext(typeof(ColodContext))]
    [Migration("20190827035832_addWordCount")]
    partial class addWordCount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CardsGame.Models.ModelColod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsChecked");

                    b.Property<string>("Name");

                    b.Property<int>("Progress");

                    b.Property<int>("WordCount");

                    b.HasKey("Id");

                    b.ToTable("ModelColods");
                });
#pragma warning restore 612, 618
        }
    }
}
